# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tiger Oakes
email: tigeroakes@gmail.com
description: > 
  My name is Tiger Oakes (yes, really). I am a programmer who creates software, 
  websites, and other things that appear on screens. 
baseurl: ""
url: "https://tigeroakes.com" # the base hostname & protocol for your site
twitter_username: Not_Woods
github_username:  NotWoods

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  projects:
    output: false

defaults:
  - scope:
      path: ""
    values:
      author: Tiger Oakes
      subtitle: ''
  - scope:
      path: ""
      type: projects
    values:
      image: null
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:title/