# Site settings
title: Tiger Oakes
email: contact@tigeroakes.com
description: >
  I'm Tiger Oakes, and I'm a software developer studying computer science
  at the University of British Columbia.
baseurl: ""
url: "https://tigeroakes.com" # the base hostname & protocol for your site
twitter_username: Not_Woods
github_username:  NotWoods
twitter:
  username: Not_Woods
facebook:
  publisher: tiger.oakes
social:
  links:
    - https://github.com/NotWoods
    - https://linkedin.com/in/tigeroakes
    - https://twitter.com/Not_Woods

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path

sass:
  sass_dir: css
  style: compressed

compress_html:
  clippings:
    - div
    - p
    - ul
    - h1
    - h2
    - h3
    - h4
    - section
    - nav
    - header
    - footer
    - meta
    - article
    - main
    - hr
    - link
  endings: [li]
  startings: [html, head, body]

defaults:
  - scope:
      path: ""
    values:
      author: tiger
      subtitle: ''

  - scope:
      path: ""
      type: projects
    values:
      images:
        logo: logo.png
        background: background.jpg
      layout: project

  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:title/
