baseURL: 'https://tigeroakes.com/'
languageCode: 'en-ca'
title: 'Tiger Oakes'
googleAnalytics: UA-37324002-1
pygmentsCodeFences: true
pygmentsStyle: dracula
pygmentsUseClasses: true

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: -125
    - identifier: projects
      name: Projects
      url: /projects/
      weight: -120
    - identifier: talks
      name: Talks
      url: /talks/
      weight: -115
    - identifier: resume
      name: Resume
      url: /resume/
      weight: -110

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML]

disableKinds:
  - taxonomy
  - taxonomyTerm

frontmatter:
  lastmod: ['lastmod', 'date', 'publishDate']

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 5

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepConditionalComments: false
      keepDefaultAttrVals: false
      keepDocumentTags: false
      keepEndTags: false
      keepWhitespace: false

server:
  headers:
    - for: /*
      values:
        Content-Security-Policy: frame-ancestors 'none'; form-action 'none'; default-src 'none'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://www.google-analytics.com; font-src https://fonts.gstatic.com; img-src 'self' https://img.shields.io; media-src 'self'; worker-src 'self'; frame-src https://www.youtube-nocookie.com https://docs.google.com; connect-src *; manifest-src 'self'; base-uri 'none'
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
    - for: /posts/index.xml
      values:
        Content-Type: application/rss+xml
