baseURL: "https://tigeroakes.com/"
languageCode: "en-ca"
title: "Tiger Oakes"
googleAnalytics: UA-37324002-1
pygmentsCodeFences: true
pygmentsStyle: dracula

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -130
    - identifier: projects
      name: Projects
      url: /projects/
      weight: -120
    - identifier: resume
      name: Resume
      url: /resume/
      weight: -110
    - identifier: blog
      name: Blog
      url: /posts/
      weight: -105
    - identifier: contact
      name: Contact
      url: /contact/
      weight: -100

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML]
  taxonomy: [HTML]
  taxonomyTerm: [HTML]
