baseURL: 'https://tigeroakes.com/'
languageCode: 'en-ca'
title: 'Tiger Oakes'
pygmentsCodeFences: true
pygmentsStyle: dracula
pygmentsUseClasses: true

contentDir: 'src/pages'
dataDir: 'src/data'

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: -125
    - identifier: projects
      name: Projects
      url: /projects/
      weight: -120
    - identifier: talks
      name: Talks
      url: /talks/
      weight: -115
    - identifier: resume
      name: Resume
      url: /resume/
      weight: -110

frontmatter:
  lastmod: ['lastmod', ':git', 'date', 'publishDate']

enableGitInfo: true

taxonomies:
  tag: tags
  category: categories

outputFormats:
  Banner:
    baseName: banner
    isPlainText: true
    mediaType: image/svg+xml
    notAlternative: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 5

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepConditionalComments: false
      keepDefaultAttrVals: false
      keepDocumentTags: false
      keepEndTags: false
      keepWhitespace: false

server:
  headers:
    - for: /*
      values:
        # prettier-ignore
        Content-Security-Policy: >
          frame-ancestors 'none';
          form-action buttondown.email;
          default-src 'none';
          style-src 'self' 'unsafe-inline';
          script-src 'self' 'unsafe-inline' https://platform.twitter.com https://caterpilla.tigeroakes.com;
          font-src 'self';
          img-src 'self' https://caterpilla.tigeroakes.com;
          media-src 'self';
          worker-src 'self';
          frame-src https://www.youtube-nocookie.com https://docs.google.com https://platform.twitter.com https://anchor.fm;
          connect-src *;
          manifest-src 'self';
          base-uri 'none'
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
    - for: /posts/index.xml
      values:
        Content-Type: application/rss+xml
