[build]
publish = "dist"
command = "npm run build"

[context.production.environment]
NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
NETLIFY_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
NETLIFY_CONTEXT = "branch-deploy"
