[build]
publish = "public"
command = "npm run build"

[build.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "12.18.3"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build -- --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "npm run build -- --gc -b $DEPLOY_PRIME_URL"
