[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "16"

[context.production.environment]
NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
NETLIFY_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
NETLIFY_CONTEXT = "branch-deploy"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  recursive = false
  checkExternal = true
