[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "lts/*"

[[edge_functions]]
path = "/.well-known/webfinger"
function = "webfinger"

[context.production.environment]
NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
NETLIFY_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
NETLIFY_CONTEXT = "branch-deploy"

[[headers]]
for = "/*"
  [headers.values]
  Feature-Policy = '''
  document-domain 'none',
  layout-animations 'none',
  legacy-image-formats 'none',
  sync-xhr 'none'
  '''
  Content-Security-Policy = '''
  frame-ancestors 'self';
  form-action buttondown.email;
  default-src 'none';
  style-src 'self' 'unsafe-inline';
  script-src 'self' 'unsafe-inline' data: https://platform.twitter.com https://cdn.usefathom.com;
  font-src 'self';
  img-src 'self' https://cdn.usefathom.com;
  media-src 'self';
  worker-src 'self';
  frame-src 'self' https://www.youtube-nocookie.com https://docs.google.com https://platform.twitter.com https://anchor.fm https://speakerdeck.com https://player.vimeo.com;
  connect-src *;
  manifest-src 'self';
  base-uri 'none'
  '''
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"

[[headers]]
for = "/posts/rss.xml"
  [headers.values]
  Content-Type = "application/rss+xml"

[[headers]]
for = "/categories/:category/rss.xml"
  [headers.values]
  Content-Type = "application/rss+xml"

[[headers]]
for = "/site.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = '''
  max-age=31536000,
  immutable'''
